version: "3.8"
services:
  web:
    image: "ghcr.io/nixrod/wichtel-tracker"
    ports:
      - "${WEB_PORT_PUBLISHED}:8080"
    restart: always
    environment:
      DB_PW: ${DB_ROOT_PW}
      HOST: db
      ADMIN_PW: ${ADMIN_PW}
  db:
    image: "mysql:latest"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}

volumes:
  db_data: {}

